accounts:
  - name: clint
    coins: ["1000000000sand","10tgld"]
  - name: kyle
    coins: ["1000000000sand","10tgld"]
  - name: m
    coins: ["1000000000sand","10tgld"]
  - name: artem
    coins: ["1000000000sand","10tgld"]
  - name: jacob
    coins: ["1000000000sand","10tgld"]
validator:
  name: jacob
  staked: "100000000sand"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
